import NLQCLean.Bounds.FiniteLocalization

/-! Full types and logical-axiom audit for actual finite localization. -/

set_option pp.universes true
set_option pp.explicit true

#check @NLQCLean.ClassicalCommunication.FinitePOVM.exists_measurementOperator
#check @NLQCLean.ClassicalCommunication.FinitePOVM.instrument
#check @NLQCLean.ClassicalCommunication.reportedLabelDecoder_isometry
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_hasQuantumFootprint_iff
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_operationalChannel_diag
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_scorePVM
#check @NLQCLean.MixedResource.ofState
#check @NLQCLean.MixedResource.densityMatrix_ofState
#check @NLQCLean.MixedResource.HasSchmidtNumberLE
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.stateReportedProbability_densityMatrix
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_hasMixedQuantumFootprint_iff
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_mixedOperationalChannel_diag
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_mixedScorePVM
#check @NLQCLean.ClassicalCommunication.ae_no_finite_exact_localization
#check @NLQCLean.ClassicalCommunication.finite_exact_localization_haar_null
#check @NLQCLean.ClassicalCommunication.finiteLocalizationReachable_subset_purePVMReachable
#check @NLQCLean.ClassicalCommunication.exists_finite_localization_haar_constant_of_external
#check @NLQCLean.ClassicalCommunication.localization_rank_rate_of_log_bound
#check @NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.stateSuccessScore_densityMatrix
#check @NLQCLean.ClassicalCommunication.LocalizationRankLowerBound
#check @NLQCLean.ClassicalCommunication.AllFiniteLocalizationRankBounds
#check @NLQCLean.ClassicalCommunication.exists_ae_finite_localization_rank_constant_of_external

#print axioms NLQCLean.ClassicalCommunication.FinitePOVM.exists_measurementOperator
#print axioms NLQCLean.ClassicalCommunication.reportedLabelDecoder_isometry
#print axioms NLQCLean.MixedResource.densityMatrix_ofState
#print axioms NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_operationalChannel_diag
#print axioms NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.stateReportedProbability_densityMatrix
#print axioms NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_mixedOperationalChannel_diag
#print axioms NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.protocol_mixedScorePVM
#print axioms NLQCLean.ClassicalCommunication.ae_no_finite_exact_localization
#print axioms NLQCLean.ClassicalCommunication.finite_exact_localization_haar_null
#print axioms NLQCLean.ClassicalCommunication.exists_finite_localization_haar_constant_of_external
#print axioms NLQCLean.ClassicalCommunication.localization_rank_rate_of_log_bound
#print axioms NLQCLean.ClassicalCommunication.FiniteLocalizationScheme.stateSuccessScore_densityMatrix
#print axioms NLQCLean.ClassicalCommunication.exists_ae_finite_localization_rank_constant_of_external
