/-
Released under Apache 2.0 license as described in the file LICENSE.
-/

import Mathlib.Algebra.MvPolynomial.Degrees
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.RingTheory.Ideal.Span
import Mathlib.Basic.Real.Basic
import Mathlib.Data.Finsupp.Weight

/-!
# Common zeros of a system with pure-power leading terms

Let `h i = X i ^ e + q i` with `q i` of total degree below `e`. Every polynomial is
congruent modulo the ideal generated by the `h i` to a linear combination of monomials
whose exponents are all below `e`. Evaluation at a finite set of common real zeros is
surjective onto all real functions on that set and vanishes on the ideal, so a finite
set of common real zeros has at most `e ^ card σ` elements.

This elementary count replaces the use of Bézout's theorem in the image-volume bound.
-/

namespace NLQCLean

open MvPolynomial Module

variable {σ : Type*} [Fintype σ] [DecidableEq σ]

/-- The monomial with exponent vector `f`, all exponents below `e`. -/
noncomputable def boxMonomial (e : ℕ) (f : σ → Fin e) : MvPolynomial σ ℝ :=
  monomial (Finsupp.equivFunOnFinite.symm fun i => (f i : ℕ)) 1

/-- The span of the monomials whose exponents are all below `e`. -/
noncomputable def boxMonomialSpan (σ : Type*) [Fintype σ] [DecidableEq σ] (e : ℕ) :
    Submodule ℝ (MvPolynomial σ ℝ) :=
  Submodule.span ℝ (Set.range (boxMonomial (σ := σ) e))

theorem monomial_mem_boxMonomialSpan {e : ℕ} {α : σ →₀ ℕ} (hα : ∀ i, α i < e) :
    monomial α (1 : ℝ) ∈ boxMonomialSpan σ e := by
  apply Submodule.subset_span
  refine ⟨fun i => ⟨α i, hα i⟩, ?_⟩
  simp only [boxMonomial]
  congr 1
  ext i
  simp

theorem finrank_boxMonomialSpan_le (e : ℕ) :
    finrank ℝ (boxMonomialSpan σ e) ≤ e ^ Fintype.card σ := by
  have h := finrank_range_le_card (R := ℝ) (boxMonomial (σ := σ) e)
  rw [Fintype.card_fun, Fintype.card_fin] at h
  exact h

instance (e : ℕ) : Module.Finite ℝ (boxMonomialSpan σ e) :=
  Module.Finite.span_of_finite ℝ (Set.finite_range _)

omit [Fintype σ] [DecidableEq σ] in
theorem degree_sum_eq_degree (α : σ →₀ ℕ) : (α.sum fun _ e => e) = α.degree := rfl

/-- Reduction modulo a system with pure-power leading terms. -/
theorem mem_boxMonomialSpan_sup_ideal {e : ℕ} (h q : σ → MvPolynomial σ ℝ)
    (hq : ∀ i, h i = X i ^ e + q i) (hdeg : ∀ i, (q i).totalDegree < e)
    (f : MvPolynomial σ ℝ) :
    f ∈ boxMonomialSpan σ e ⊔ (Ideal.span (Set.range h)).restrictScalars ℝ := by
  set W := boxMonomialSpan σ e ⊔ (Ideal.span (Set.range h)).restrictScalars ℝ
  have hpoly : ∀ n : ℕ, (∀ α : σ →₀ ℕ, α.degree < n → monomial α (1 : ℝ) ∈ W) →
      ∀ g : MvPolynomial σ ℝ, g.totalDegree < n → g ∈ W := by
    intro n hn g hg
    rw [g.as_sum]
    refine Submodule.sum_mem _ fun α hα => ?_
    have hm : monomial α (g.coeff α) = g.coeff α • monomial α (1 : ℝ) := by
      rw [smul_monomial, smul_eq_mul, mul_one]
    rw [hm]
    refine Submodule.smul_mem _ _ (hn α ?_)
    rw [← degree_sum_eq_degree]
    exact (le_totalDegree hα).trans_lt hg
  have hmono : ∀ n : ℕ, ∀ α : σ →₀ ℕ, α.degree = n → monomial α (1 : ℝ) ∈ W := by
    intro n
    induction n using Nat.strong_induction_on with
    | _ n ih =>
      intro α hα
      by_cases hred : ∀ i, α i < e
      · exact Submodule.mem_sup_left (monomial_mem_boxMonomialSpan hred)
      · push Not at hred
        obtain ⟨i, hi⟩ := hred
        set β : σ →₀ ℕ := α - Finsupp.single i e with hβ
        have hαβ : α = β + Finsupp.single i e := by
          ext j
          by_cases hj : j = i
          · subst hj
            simp [hβ, Nat.sub_add_cancel hi]
          · simp [hβ, Ne.symm hj]
        have hm : monomial α (1 : ℝ) = monomial β 1 * h i - monomial β 1 * q i := by
          rw [hq i, mul_add, add_sub_cancel_right, X_pow_eq_monomial, monomial_mul_monomial, one_mul,
            ← hαβ]
        rw [hm]
        refine Submodule.sub_mem _ ?_ ?_
        · apply Submodule.mem_sup_right
          rw [Submodule.restrictScalars_mem]
          exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)
        · have hβdeg : α.degree = β.degree + e := by
            rw [hαβ, map_add, Finsupp.degree_single]
          refine hpoly n (fun γ hγ => ih _ hγ γ rfl) _ ?_
          calc (monomial β (1 : ℝ) * q i).totalDegree
              ≤ (monomial β (1 : ℝ)).totalDegree + (q i).totalDegree := totalDegree_mul _ _
            _ < β.degree + e := by
              rw [totalDegree_monomial _ one_ne_zero, degree_sum_eq_degree]
              have := hdeg i
              omega
            _ = n := by rw [← hβdeg, hα]
  exact hpoly (f.totalDegree + 1) (fun α _ => hmono _ α rfl) f (Nat.lt_succ_self _)

omit [DecidableEq σ] in
/-- Polynomial interpolation on a finite set of points. -/
theorem exists_mvPolynomial_eval_eq_indicator (V : Finset (σ → ℝ)) {v : σ → ℝ} (hv : v ∈ V) :
    ∃ P : MvPolynomial σ ℝ, ∀ w ∈ V, eval w P = if w = v then 1 else 0 := by
  classical
  have hsep : ∀ w : σ → ℝ, w ≠ v → ∃ j, v j ≠ w j := fun w hw => by
    by_contra! H
    exact hw (funext fun j => (H j).symm)
  refine ⟨∏ w ∈ V.erase v, if hw : w = v then 1 else
      C (v (Classical.choose (hsep w hw)) - w (Classical.choose (hsep w hw)))⁻¹ *
        (X (Classical.choose (hsep w hw)) - C (w (Classical.choose (hsep w hw)))), ?_⟩
  intro u hu
  rw [map_prod]
  split_ifs with huv
  · subst huv
    refine Finset.prod_eq_one fun w hw => ?_
    have hwv : w ≠ u := Finset.ne_of_mem_erase hw
    rw [dite_eq_right hwv]
    simp only [map_mul, eval_C, map_sub, eval_X]
    exact inv_mul_cancel₀ (sub_ne_zero.mpr (Classical.choose_spec (hsep w hwv)))
  · refine Finset.prod_eq_zero (Finset.mem_erase.mpr ⟨huv, hu⟩) ?_
    rw [dite_eq_right huv]
    simp

/-- A finite set of common real zeros of `X i ^ e + q i`, with `deg q i < e`,
has at most `e ^ card σ` points. -/
theorem card_le_of_forall_eval_eq_zero {e : ℕ} (h q : σ → MvPolynomial σ ℝ)
    (hq : ∀ i, h i = X i ^ e + q i) (hdeg : ∀ i, (q i).totalDegree < e)
    (V : Finset (σ → ℝ)) (hV : ∀ v ∈ V, ∀ i, eval v (h i) = 0) :
    V.card ≤ e ^ Fintype.card σ := by
  classical
  let ev : MvPolynomial σ ℝ →ₗ[ℝ] (V → ℝ) :=
    { toFun := fun f v => eval (v : σ → ℝ) f
      map_add' := fun f g => by ext v; simp
      map_smul' := fun c f => by ext v; simp }
  have hker : (Ideal.span (Set.range h)).restrictScalars ℝ ≤ LinearMap.ker ev := by
    intro f hf
    rw [Submodule.restrictScalars_mem] at hf
    rw [LinearMap.mem_ker]
    ext v
    have hle : Ideal.span (Set.range h) ≤ RingHom.ker (eval (v : σ → ℝ)) := by
      rw [Ideal.span_le]
      rintro _ ⟨i, rfl⟩
      exact hV v v.2 i
    exact hle hf
  have hsurj : Function.Surjective ev := by
    intro g
    choose P hP using fun v : V => exists_mvPolynomial_eval_eq_indicator V v.2
    refine ⟨∑ v : V, g v • P v, ?_⟩
    ext u
    simp only [ev, LinearMap.coe_mk, AddHom.coe_mk, map_sum, map_smul, Finset.sum_apply,
      Pi.smul_apply, smul_eq_mul]
    rw [Finset.sum_eq_single u]
    · rw [hP u u u.2, ite_eq_left rfl, mul_one]
    · intro v _ hvu
      rw [hP v u u.2, ite_eq_right (fun h => hvu (Subtype.ext h).symm), mul_zero]
    · simp
  have hrange : LinearMap.range ev = (boxMonomialSpan σ e).map ev := by
    apply le_antisymm
    · rintro _ ⟨f, rfl⟩
      obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp
        (mem_boxMonomialSpan_sup_ideal h q hq hdeg f)
      rw [map_add, LinearMap.mem_ker.mp (hker hb), add_zero]
      exact Submodule.mem_map_of_mem ha
    · exact LinearMap.map_le_range
  have htop : LinearMap.range ev = ⊤ := LinearMap.range_eq_top.mpr hsurj
  calc V.card = finrank ℝ (V → ℝ) := by simp
    _ = finrank ℝ (LinearMap.range ev) := by rw [htop, finrank_top]
    _ = finrank ℝ ((boxMonomialSpan σ e).map ev) := by rw [hrange]
    _ ≤ finrank ℝ (boxMonomialSpan σ e) := Submodule.finrank_map_le _ _
    _ ≤ e ^ Fintype.card σ := finrank_boxMonomialSpan_le e

end NLQCLean
